import type {ActivationImage} from '~/lib/activations';

export const APOC_EVENT_GALLERY: ActivationImage[] = [
  {id: 'apoc-ev-01', url: '/images/activations/apoc/apoc-ev-01.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1066, height: 1600},
  {id: 'apoc-ev-02', url: '/images/activations/apoc/apoc-ev-02.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1066, height: 1600},
  {id: 'apoc-ev-03', url: '/images/activations/apoc/apoc-ev-03.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1066, height: 1600},
  {id: 'apoc-ev-04', url: '/images/activations/apoc/apoc-ev-04.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1066, height: 1600},
  {id: 'apoc-ev-05', url: '/images/activations/apoc/apoc-ev-05.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1066, height: 1600},
  {id: 'apoc-ev-06', url: '/images/activations/apoc/apoc-ev-06.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1066, height: 1600},
  {id: 'apoc-ev-07', url: '/images/activations/apoc/apoc-ev-07.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1066, height: 1600},
  {id: 'apoc-ev-08', url: '/images/activations/apoc/apoc-ev-08.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1600, height: 1066},
  {id: 'apoc-ev-09', url: '/images/activations/apoc/apoc-ev-09.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1600, height: 1066},
  {id: 'apoc-ev-10', url: '/images/activations/apoc/apoc-ev-10.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1066, height: 1600},
  {id: 'apoc-ev-11', url: '/images/activations/apoc/apoc-ev-11.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1066, height: 1600},
  {id: 'apoc-ev-12', url: '/images/activations/apoc/apoc-ev-12.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1066, height: 1600},
  {id: 'apoc-ev-13', url: '/images/activations/apoc/apoc-ev-13.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1066, height: 1600},
  {id: 'apoc-ev-14', url: '/images/activations/apoc/apoc-ev-14.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1066, height: 1600},
  {id: 'apoc-ev-15', url: '/images/activations/apoc/apoc-ev-15.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1066, height: 1600},
  {id: 'apoc-ev-16', url: '/images/activations/apoc/apoc-ev-16.jpg', altText: "APOC's US Debut × NOTHING Ear(3) at Earshot, NYFW 2025 — photo: Colin Savercool", width: 1066, height: 1600},
];

export const APOC_OFFICE_GALLERY: ActivationImage[] = [
  {id: 'apoc-off-01', url: '/images/activations/apoc/apoc-off-01.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-02', url: '/images/activations/apoc/apoc-off-02.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-03', url: '/images/activations/apoc/apoc-off-03.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1600, height: 1066},
  {id: 'apoc-off-04', url: '/images/activations/apoc/apoc-off-04.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-05', url: '/images/activations/apoc/apoc-off-05.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-06', url: '/images/activations/apoc/apoc-off-06.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-07', url: '/images/activations/apoc/apoc-off-07.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-08', url: '/images/activations/apoc/apoc-off-08.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-09', url: '/images/activations/apoc/apoc-off-09.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-10', url: '/images/activations/apoc/apoc-off-10.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-11', url: '/images/activations/apoc/apoc-off-11.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-12', url: '/images/activations/apoc/apoc-off-12.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-13', url: '/images/activations/apoc/apoc-off-13.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-14', url: '/images/activations/apoc/apoc-off-14.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-15', url: '/images/activations/apoc/apoc-off-15.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1600, height: 1066},
  {id: 'apoc-off-16', url: '/images/activations/apoc/apoc-off-16.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-17', url: '/images/activations/apoc/apoc-off-17.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-18', url: '/images/activations/apoc/apoc-off-18.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-19', url: '/images/activations/apoc/apoc-off-19.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-20', url: '/images/activations/apoc/apoc-off-20.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1280, height: 1600},
  {id: 'apoc-off-21', url: '/images/activations/apoc/apoc-off-21.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1600, height: 1200},
  {id: 'apoc-off-22', url: '/images/activations/apoc/apoc-off-22.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1600, height: 1200},
  {id: 'apoc-off-23', url: '/images/activations/apoc/apoc-off-23.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1600, height: 1200},
  {id: 'apoc-off-24', url: '/images/activations/apoc/apoc-off-24.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1600, height: 1200},
  {id: 'apoc-off-25', url: '/images/activations/apoc/apoc-off-25.jpg', altText: "APOC's US Debut × NOTHING Ear(3), NYFW 2025 — photography courtesy of APOC via Office Magazine", width: 1199, height: 1600},
];
